### ISSUE TITLE
wrapped

### ISSUE THREAD

**Issue by stdlib-h** [gurkult/gurkbot#80]
for wrapping.yml maybe we can add more header files or import more classes by

```yml
c: "#include <stdio.h>\n#include <math.h>\nint main() {code}"
cpp: "#include <iostream>\n#include <cmath>\nint main() {code}"
cs: "using System;class Program {static void Main(string[] args) {code}}"
java: "import java.util.Random;\npublic class Main {public static void main(String[] args) {code}}"
rust: "fn main() {code}"
d: "import std.stdio; void main(){code}"
kotlin: "fun main(args: Array<String>) {code}"
```
and add more for the other languages
